-- =====================================================================
-- Construction de la table analytique de scoring churn (Snowflake)
-- Version anonymisee pour portfolio (contexte professionnel).
-- Tables/schemas internes, codes produits/classification/reseau, noms de
-- colonnes source et identifiants clients remplaces par des valeurs
-- generiques. Non executable en l'etat (pas de donnees).
-- =====================================================================

--2024 CHURN
SET DATE_REF = '2024-12-31';
CREATE OR REPLACE TABLE LAB.SCORE_CHURN_2024 AS
WITH CLASSIFICATIONS AS (
    SELECT
        CLIENTS.ID_CLIENT,
        /*exclusion client ss tutelle*/
        COALESCE(MAX(CLASSIF_TIERS.CODE_TYPE_CLASSIF = 'PP'
            AND CLASSIF_TIERS.CODE_CLASSIF NOT LIKE 'D%'), FALSE) AS IND_SOUS_TUTELLE,
        /*exclusion client fragile*/
        COALESCE(MAX(CLASSIF_TIERS.CODE_CLASSIF IN ('XXXX','XXXX','XXXX')), FALSE) AS IND_FRAGILE,
        /*exclusion client en contentieux*/
        COALESCE(MAX(CLASSIF_TIERS.CODE_CLASSIF = 'CONT'),FALSE) AS "INDICATEUR CLIENT CONTENTIEUX",
        /* client banque patrimoniale*/
        COALESCE(MAX(CLASSIF_TIERS.CODE_CLASSIF IN ('XXXX','XXXX')), FALSE) AS IND_BANQUE_PATRIMONIALE

    FROM DWH.CLIENTS
    LEFT JOIN DWH.CLASSIF_TIERS
        ON CLIENTS.ID_CLIENT = CLASSIF_TIERS.ID_CLIENT
    WHERE DATE_TRUNC('month', CLIENTS.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
    GROUP BY CLIENTS.ID_CLIENT
),
POPULATION_BASE AS(
    SELECT
        T1.ID_CLIENT,
        T1.IN_CONT_VIE,
        T1.DATE_PREMIER_CONTRAT
    FROM DWH.CLIENTS T1
    LEFT JOIN CLASSIFICATIONS T2
        ON T1.ID_CLIENT = T2.ID_CLIENT
    WHERE DATE_TRUNC('month', T1.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
        --client actif (en vie)
        AND T1.IN_CONT_VIE = 'TRUE'
        --client decede
        AND T1.IN_CLNT_DECD = 'FALSE'
        -- ANCIENNETE >= 2 ans
        AND DATEDIFF('year', T1.DATE_PREMIER_CONTRAT, TO_DATE($DATE_REF)) >= 2
        -- clients ss tutelle
        AND T2.IND_SOUS_TUTELLE = FALSE
        --clients risqué
        AND T2.IND_FRAGILE = FALSE
        --clients PP
        AND EXISTS (
            SELECT 1
            FROM DWH.TIERS T3
            WHERE T3.ID_CLIENT = T1.ID_CLIENT
            AND T3.CODE_TYPE_PERSONNE = 'P')
        AND EXISTS (
            SELECT 1
            FROM DWH.CONTRATS
            WHERE ID_CLIENT = T1.ID_CLIENT
            AND DATE_TRUNC('month', DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
        )
),

SOURCE_ENCOURS AS (
    SELECT ID_CLIENT, MONTANT_ENCOURS, DATE_TRUNC('month', DATE_CHARGEMENT) AS MOIS
    FROM DWH.EPARGNE_BANCAIRE
    WHERE DATE_TRUNC('month', DATE_CHARGEMENT)
        BETWEEN DATE_TRUNC('month', DATEADD('month', -12, TO_DATE($DATE_REF)))
            AND DATE_TRUNC('month', TO_DATE($DATE_REF))
    AND CODE_PRODUIT_CATALOGUE IN (
        'XXXXX',  -- COMPTE COURANT
        'XXXXX',  -- COMPTE COURANT
        'XXXXX',  -- COMPTE COURANT
        'XXXXX',  -- COMPTE COURANT
        'XXXXX',  -- COMPTE COURANT
        'XXXXX',  -- LIVRET EPARGNE
        'XXXXX',  -- LIVRET A
        'XXXXX',  -- LIVRET DEV. DURABLE ET SOLIDAIRE
        'XXXXX',  -- PLAN EPARGNE LOGEMENT
        'XXXXX'   -- COMPTE EPARGNE LOGEMENT
    )

    UNION ALL

    SELECT ID_CLIENT, MONTANT_ENCOURS, DATE_TRUNC('month', DATE_CHARGEMENT) AS MOIS
    FROM DWH.EPARGNE_FINANCIERE
    WHERE DATE_TRUNC('month', DATE_CHARGEMENT)
        BETWEEN DATE_TRUNC('month', DATEADD('month', -12, TO_DATE($DATE_REF)))
            AND DATE_TRUNC('month', TO_DATE($DATE_REF))
    AND CODE_PRODUIT_CATALOGUE IN (
        'XXXXX',  -- COMPTE TITRES
        'XXXXX'   -- PLAN D EPARGNE EN ACTIONS
    )
    --('XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX')
),
-- encours total par client par mois
ENCOURS_PAR_MOIS AS (
    SELECT
        ID_CLIENT,
        MOIS,
        SUM(MONTANT_ENCOURS) AS ENCOURS_MOIS
    FROM SOURCE_ENCOURS
    GROUP BY ID_CLIENT, MOIS
),
-- pivot (une ligne par client mtn) + moyenne + ecart-type par client
ENCOURS_FINAL AS (
    SELECT
        ID_CLIENT,
        /*encours actuel*/
        SUM(CASE WHEN MOIS = DATE_TRUNC('month', TO_DATE($DATE_REF))
            THEN ENCOURS_MOIS ELSE 0 END) AS ENCOURS_M,
        /*encours - 1 mois*/
        SUM(CASE WHEN MOIS = DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN ENCOURS_MOIS ELSE 0 END
        ) AS "ENCOURS M-1",
        /*encours - 2 mois*/
        SUM(CASE WHEN MOIS = DATE_TRUNC('month', DATEADD('month', -2, TO_DATE($DATE_REF)))
            THEN ENCOURS_MOIS ELSE 0 END) AS "ENCOURS M-2",
        /*encours - 3 mois*/
        SUM(CASE WHEN MOIS = DATE_TRUNC('month', DATEADD('month', -3, TO_DATE($DATE_REF)))
            THEN ENCOURS_MOIS ELSE 0 END) AS "ENCOURS M-3",
        /*moyenne annuelle encours*/
        AVG(ENCOURS_MOIS) AS MOY_ENCOURS_12M,
        /*ecart type sur 12 mois*/
        STDDEV(ENCOURS_MOIS) AS ECART_TYPE_ENCOURS_12M

    FROM ENCOURS_PAR_MOIS
    GROUP BY ID_CLIENT
),
ENCOURS_PM AS (
    SELECT DISTINCT
        TIERS_PM.ID_TIERS_LIE,
        TRUE AS "INDICATEUR CLIENT REPRESENTANT LEGAL PM",
        COALESCE(SUM(CASE WHEN TRIM(FAMILLE_PRODUIT) = 'COMPTE'
            THEN EPARGNE_BANCAIRE.MONTANT_ENCOURS
            ELSE 0 END), 0) AS "ENCOURS COMPTE PM",
        COALESCE(SUM(CASE WHEN TRIM(FAMILLE_PRODUIT) = 'EPARGNE'
            THEN EPARGNE_BANCAIRE.MONTANT_ENCOURS
            ELSE 0 END), 0) AS "ENCOURS EPARGNE PM"
    FROM DWH.TIERS_PM
    INNER JOIN DWH.CLIENTS
        ON TIERS_PM.ID_CLIENT = CLIENTS.ID_CLIENT
    INNER JOIN DWH.CONTRATS
        ON CONTRATS.ID_CLIENT = TIERS_PM.ID_CLIENT
    INNER JOIN LAB.REFERENTIEL_PRODUITS
        ON CONTRATS.CODE_PRODUIT_CATALOGUE = REFERENTIEL_PRODUITS.CODE_PRODUIT_CATALOGUE
    LEFT JOIN DWH.EPARGNE_BANCAIRE
        ON CONTRATS.ID_CONTRAT_SOUSCRIT = EPARGNE_BANCAIRE.ID_CONTRAT_SOUSCRIT
    -- decoupage avec epargne fi
    WHERE DATE_TRUNC('month', CONTRATS.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
        AND DATE_TRUNC('month', CLIENTS.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
        AND DATE_TRUNC('month', EPARGNE_BANCAIRE.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
        AND CONTRATS.IN_EN_VIE = TRUE
        AND CLIENTS.IN_CONT_VIE = TRUE
        AND TRIM(TYPE_CONTRAT_CATALOGUE) = 'PRODUIT'
        AND ID_TIERS_LIE IS NOT NULL
    GROUP BY TIERS_PM.ID_TIERS_LIE
),
PRODUITS_CLIENT AS (
    SELECT
        CONTRATS.ID_CLIENT,
        -- NOMBRE DE PRODUIT PAR CLIENT
        COUNT(DISTINCT CASE WHEN TRIM(REF_PRODUIT_MARKET.TYPE_CONTRAT_CATALOGUE) = 'PRODUIT'
            AND CONTRATS.IN_EN_VIE = TRUE
            THEN CONTRATS.ID_CONTRAT_SOUSCRIT END) AS "NOMBRE PRODUITS",
        -- NOMBRE FAMILLE DE PRODUIT PAR CLIENT
        COUNT(DISTINCT CASE WHEN TRIM(REF_PRODUIT_MARKET.TYPE_CONTRAT_CATALOGUE) = 'PRODUIT'
            AND CONTRATS.IN_EN_VIE = TRUE
            THEN TRIM(REF_PRODUIT_MARKET.FAMILLE_PRODUIT) END) AS "NOMBRE FAMILLES PRODUITS",
        -- INDICATEUR CREDIT IMMOBILIER
        COUNT(DISTINCT CASE WHEN TRIM(REF_PRODUIT_MARKET.PRODUIT) = 'CREDIT IMMOBILIER'
            AND CONTRATS.IN_EN_VIE = TRUE
            THEN CONTRATS.ID_CONTRAT_SOUSCRIT END) > 0 AS "INDICATEUR CLIENT CREDIT IMMOBILIER",
        -- MONO DETENTEUR
        COUNT(DISTINCT CASE WHEN TRIM(REF_PRODUIT_MARKET.TYPE_CONTRAT_CATALOGUE) = 'PRODUIT'
            AND CONTRATS.IN_EN_VIE = TRUE
            THEN CONTRATS.ID_CONTRAT_SOUSCRIT END) = 1 AS "INDICATEUR CLIENT MONO DETENTEUR",
        --INDICATEUR CLIENT PACK PREMIUM
        COUNT(DISTINCT CASE    WHEN TRIM(REF_PRODUIT_MARKET.PRODUIT) = 'PACK PREMIUM'
            AND CONTRATS.IN_EN_VIE = TRUE
            THEN CONTRATS_EQUIPEMENT.ID_CONTRAT_EQUIPEMENT END) > 0 AS "INDICATEUR CLIENT PREMIUM"
    FROM DWH.CONTRATS
    LEFT JOIN LAB.REFERENTIEL_PRODUITS REF_PRODUIT_MARKET
        ON CONTRATS.CODE_PRODUIT_CATALOGUE = REF_PRODUIT_MARKET.CODE_PRODUIT_CATALOGUE
    LEFT JOIN DWH.CONTRATS_EQUIPEMENT ON CONTRATS.ID_CONTRAT_SOUSCRIT = CONTRATS_EQUIPEMENT.ID_CONTRAT_EQUIPEMENT
    WHERE DATE_TRUNC('month', CONTRATS.DATE_CHARGEMENT) = DATE_TRUNC('month', TO_DATE($DATE_REF))
    GROUP BY CONTRATS.ID_CLIENT
),
PROFIL_CLIENT AS(
    SELECT
        T1.ID_CLIENT,
        -- ANCIENNETE CLIENT
        DATEDIFF('year', T2.DATE_ENREGISTREMENT_CLIENT, TO_DATE($DATE_REF)) AS "ANCIENNETE CLIENT",
        --CANAL CLIENT
        CASE WHEN T2.CODE_POPULATION_CLIENT IN('XXX','XXX','XXX','XXX') THEN 'INTERMEDIE' ELSE 'DIRECT' END AS "CANAL CLIENT",
        -- RESEAU CLIENT
        CASE WHEN T2.CODE_POPULATION_CLIENT IS NULL THEN 'DIRECT'
            WHEN T2.CODE_POPULATION_CLIENT = 'XXX' THEN 'XXX'
            WHEN T2.CODE_POPULATION_CLIENT = 'XXX' THEN 'XXX'
            WHEN T2.CODE_POPULATION_CLIENT = 'XXX' THEN 'XXX'
            WHEN T2.CODE_POPULATION_CLIENT = 'XXX' THEN 'COURTIER' END AS "RESEAU CLIENT",
        -- CSP
        CASE WHEN T5.CODE_CSP IN ('XXXXX') THEN 'Retraités'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX') OR (T5.CODE_CSP IS NULL) THEN 'Etudiants'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX') THEN 'Agriculteurs exploitants'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX') THEN 'Artisans, commerçants et chefs d entr.'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX','XXXXX','XXXXX') THEN 'Employés'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX') THEN 'Cadres, professions sup'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX') THEN 'Ouvriers'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX','XXXXX') THEN 'Chomeurs, inactifs'
            WHEN T5.CODE_CSP IN ('XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX','XXXXX') THEN 'Profession intermédiaire'
        END AS "CSP",
        -- NOMBRE ENFANT A CHARGE
        CAST(T5.NB_ENFANTS_CHARGE AS NUMBER) AS "NOMBRE ENFANTS A CHARGE",
        -- CLIENT VIP
        T2.IN_CLNT_VIP AS "INDICATEUR CLIENT VIP",
        COALESCE(IN_DETN_EML = TRUE AND CODE_ACCEPT_EMAIL = 'Y', FALSE) AS "INDICATEUR CLIENT EMAILABLE",
        COALESCE(IN_DETN_ADRS = TRUE AND CODE_ACCEPT_COURRIER = 'Y' AND CODE_POSTAL IS NOT NULL, FALSE) AS "INDICATEUR CLIENT MAILABLE",
        COALESCE(IN_DETN_PORT = TRUE AND CODE_ACCEPT_SMS = 'Y', FALSE) AS "INDICATEUR CLIENT PHONABLE SMS",
        COALESCE(IN_DETN_TELP = TRUE AND CODE_ACCEPT_TEL = 'Y', FALSE) AS "INDICATEUR CLIENT PHONABLE"

    FROM POPULATION_BASE T1
    LEFT JOIN DWH.TIERS T2 ON T1.ID_CLIENT = T2.ID_CLIENT
    LEFT JOIN PRODUITS_CLIENT T4 ON T1.ID_CLIENT = T4.ID_CLIENT
    LEFT JOIN DWH.TIERS_PP T5 ON T1.ID_CLIENT = T5.ID_CLIENT
),
SOURCE_MVNT AS (
    SELECT
        ID_CLIENT,
        DATE_TRUNC('month', DATE_OPERATION) AS MOIS,
        -- MONTANT CREDITEUR PAR MOIS
        SUM(CASE WHEN MONTANT_OPERATION_DEVISE >= 0 THEN ROUND(MONTANT_OPERATION_DEVISE, 0) ELSE 0 END) AS CREDIT_MOIS,
        -- MONTANT DEBITEUR PAR MOIS
        SUM(CASE WHEN MONTANT_OPERATION_DEVISE < 0 THEN ROUND(MONTANT_OPERATION_DEVISE,0) ELSE 0 END) AS DEBIT_MOIS
    FROM DWH.OPERATIONS_CAV
    WHERE DATE_OPERATION >= DATEADD('month', -12, TO_DATE($DATE_REF))
        AND DATE_OPERATION < TO_DATE($DATE_REF)
        AND LB_OPRT_1 NOT LIKE '%CARTE%'
    GROUP BY ID_CLIENT, DATE_TRUNC('month', DATE_OPERATION)
),

MVNT_FINAL AS (
    SELECT
        ID_CLIENT,
        -- mouvements par fenetre
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN CREDIT_MOIS ELSE 0 END) AS "MONTANT CREDITEUR 1M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -6, TO_DATE($DATE_REF)))
            THEN CREDIT_MOIS ELSE 0 END) AS "MONTANT CREDITEUR 6M",
        SUM(CREDIT_MOIS) AS "MONTANT CREDITEUR 12M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN DEBIT_MOIS ELSE 0 END) AS "MONTANT DEBITEUR 1M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -6, TO_DATE($DATE_REF)))
            THEN DEBIT_MOIS ELSE 0 END) AS "MONTANT DEBITEUR 6M",
        SUM(DEBIT_MOIS) AS "MONTANT DEBITEUR 12M",
        -- MONTANT CREDITEUR M-1 pour le zscore
        SUM(CASE WHEN MOIS = DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN CREDIT_MOIS ELSE 0 END) AS "MONTANT CREDITEUR M-1",
        -- moyenne et ecart-type sur 12 mois
        AVG(CREDIT_MOIS) AS MOY_CREDIT_12M,
        STDDEV(CREDIT_MOIS) AS ECART_TYPE_CREDIT_12M,
        AVG(DEBIT_MOIS) AS MOY_DEBIT_12M,
        STDDEV(DEBIT_MOIS) AS ECART_TYPE_DEBIT_12M
    FROM SOURCE_MVNT
    GROUP BY ID_CLIENT
),
MVNT_CARTE AS(
    SELECT
        ID_CLIENT,
        DATE_TRUNC('month', DATE_ACHAT) AS MOIS,
        SUM(CASE WHEN MONTANT_OPERATION > 0 THEN MONTANT_OPERATION ELSE 0 END) AS DEBIT_CARTE_MOIS,
        COUNT(CASE WHEN MONTANT_OPERATION > 0 THEN 1 END) AS NBR_DEBIT_CARTE_MOIS
    FROM DWH.OPERATIONS_CARTE
    WHERE DATE_ACHAT >= DATEADD('month', -12, TO_DATE($DATE_REF))
        AND DATE_ACHAT < TO_DATE($DATE_REF)
        AND CODE_SENS_OPERATION = 'D'
    GROUP BY ID_CLIENT, DATE_TRUNC('month', DATE_ACHAT)
),
MVNT_FINAL_CARTE AS(
    SELECT
        ID_CLIENT,
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN DEBIT_CARTE_MOIS ELSE 0 END) AS "MONTANT_DEBITEUR_1M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -6, TO_DATE($DATE_REF)))
            THEN DEBIT_CARTE_MOIS ELSE 0 END) AS "MONTANT_DEBITEUR_6M",
        SUM(DEBIT_CARTE_MOIS) AS "MONTANT_DEBITEUR_12M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -1, TO_DATE($DATE_REF)))
            THEN NBR_DEBIT_CARTE_MOIS ELSE 0 END) AS "NBR_DEBIT_CARTE_1M",
        SUM(CASE WHEN MOIS >= DATE_TRUNC('month', DATEADD('month', -6, TO_DATE($DATE_REF)))
            THEN NBR_DEBIT_CARTE_MOIS ELSE 0 END) AS "NBR_DEBIT_CARTE_6M",
        SUM(NBR_DEBIT_CARTE_MOIS) AS "NBR_DEBIT_CARTE_12M",
        AVG(DEBIT_CARTE_MOIS) AS MOY_DEBIT_CARTE_12M,
        STDDEV(DEBIT_CARTE_MOIS) AS ECART_TYPE_DEBIT_CARTE_12M
    FROM MVNT_CARTE
    GROUP BY ID_CLIENT
),
CONNEXIONS AS (
    SELECT
        CONNEXIONS_WEB.ID_CLIENT,
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE = 'XXX'
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION WEB 12M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE IN ('ANDROID','IPHONE')
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION APPLI 12M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE = 'XXX'
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -6, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION WEB 6M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE IN ('ANDROID','IPHONE')
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -6, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION APPLI 6M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE = 'XXX'
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -1, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION WEB 1M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE IN ('ANDROID','IPHONE')
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -1, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION APPLI 1M",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE IN ('ANDROID','IPHONE')
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -5, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < DATEADD('month', -2, TO_DATE($DATE_REF))
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION APPLI T3",
        COUNT(DISTINCT CASE WHEN CONNEXIONS_WEB_REF.CODE_SERVICE IN ('ANDROID','IPHONE')
            AND CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -2, TO_DATE($DATE_REF))
            AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
            THEN ID_CONNEXION_WEB END) AS "NOMBRE CONNEXION APPLI T4"
    FROM DWH.CONNEXIONS_WEB
    LEFT JOIN DWH.CONNEXIONS_WEB_REF
        ON CONNEXIONS_WEB.ID_HISTORIQUE_ACCES = CONNEXIONS_WEB_REF.ID_HISTORIQUE_ACCES
        AND CONNEXIONS_WEB.DATE_ACCES = CONNEXIONS_WEB_REF.DATE_ACCES
    WHERE CONNEXIONS_WEB.DATE_ACCES >= DATEADD('month', -12, TO_DATE($DATE_REF))
        AND CONNEXIONS_WEB.DATE_ACCES < TO_DATE($DATE_REF)
    GROUP BY CONNEXIONS_WEB.ID_CLIENT
),
VARIABLE_Y AS (
    SELECT
        ID_CLIENT,
        -- Y = 1 si le client n'a plus de contrat en vie a un moment dans la fenetre
        MAX(CASE WHEN IN_CONT_VIE = FALSE THEN 1 ELSE 0 END) AS Y
    FROM DWH.CLIENTS
    WHERE DATE_TRUNC('month', DATE_CHARGEMENT) > DATE_TRUNC('month', TO_DATE($DATE_REF))
        AND DATE_TRUNC('month', DATE_CHARGEMENT) <= DATE_TRUNC('month', DATEADD('month', 12, TO_DATE($DATE_REF)))
    GROUP BY ID_CLIENT
)

SELECT

    T3.ID_CLIENT,
    -- PROFIL CLIENT
    T4."ANCIENNETE CLIENT",
    T4."CANAL CLIENT",
    T4."RESEAU CLIENT",
    T4."CSP",
    T4."NOMBRE ENFANTS A CHARGE",
    T4."INDICATEUR CLIENT VIP",
    T4."INDICATEUR CLIENT EMAILABLE",
    T4."INDICATEUR CLIENT MAILABLE",
    T4."INDICATEUR CLIENT PHONABLE SMS",
    T4."INDICATEUR CLIENT PHONABLE",

    -- CLASSIFICATIONS
    T6.IND_BANQUE_PATRIMONIALE,
    T6."INDICATEUR CLIENT CONTENTIEUX",

    -- PRODUITS
    T7."NOMBRE PRODUITS",
    T7."NOMBRE FAMILLES PRODUITS",
    T7."INDICATEUR CLIENT CREDIT IMMOBILIER",
    T7."INDICATEUR CLIENT MONO DETENTEUR",
    T7."INDICATEUR CLIENT PREMIUM",

    -- ENCOURS
    COALESCE(T5.ENCOURS_M, 0) AS ENCOURS_M,
    COALESCE(T5."ENCOURS M-1", 0) AS "ENCOURS M-1",
    COALESCE(T5."ENCOURS M-2", 0) AS "ENCOURS M-2",
    COALESCE(T5."ENCOURS M-3", 0) AS "ENCOURS M-3",
    ROUND(COALESCE(T5.MOY_ENCOURS_12M, 0),0) AS MOY_ENCOURS_12M,
    T5.ECART_TYPE_ENCOURS_12M,
    CASE WHEN T5.MOY_ENCOURS_12M > 10 OR T5.MOY_ENCOURS_12M < -10
        THEN ROUND(T5.ENCOURS_M / T5.MOY_ENCOURS_12M, 2)
        ELSE 0 END AS RATIO_ENCOURS_M_MOY12M,
    CASE WHEN T5.ECART_TYPE_ENCOURS_12M > 1
        THEN ROUND((T5.ENCOURS_M - T5.MOY_ENCOURS_12M) / T5.ECART_TYPE_ENCOURS_12M, 2)
        ELSE 0 END AS ZSCORE_ENCOURS_M,
    -- ENCOURS PM
    COALESCE(T11."INDICATEUR CLIENT REPRESENTANT LEGAL PM", FALSE) AS "INDICATEUR CLIENT REPRESENTANT LEGAL PM",
    COALESCE(T11."ENCOURS COMPTE PM", 0) AS "ENCOURS COMPTE PM",
    COALESCE(T11."ENCOURS EPARGNE PM", 0) AS "ENCOURS EPARGNE PM",

    -- MOUVEMENTS CAV
    COALESCE(T8."MONTANT CREDITEUR 1M", 0) AS "MONTANT CREDITEUR 1M",
    COALESCE(T8."MONTANT CREDITEUR 6M", 0) AS "MONTANT CREDITEUR 6M",
    COALESCE(T8."MONTANT CREDITEUR 12M", 0) AS "MONTANT CREDITEUR 12M",
    COALESCE(T8."MONTANT DEBITEUR 1M", 0) AS "MONTANT DEBITEUR 1M",
    COALESCE(T8."MONTANT DEBITEUR 6M", 0) AS "MONTANT DEBITEUR 6M",
    COALESCE(T8."MONTANT DEBITEUR 12M", 0) AS "MONTANT DEBITEUR 12M",
    COALESCE(T8."MONTANT CREDITEUR M-1", 0) AS "MONTANT CREDITEUR M-1",
    COALESCE(T8.MOY_CREDIT_12M, 0) AS MOY_CREDIT_12M,
    T8.ECART_TYPE_CREDIT_12M,
    COALESCE(T8.MOY_DEBIT_12M, 0) AS MOY_DEBIT_12M,
    T8.ECART_TYPE_DEBIT_12M,
    CASE WHEN T8.MOY_CREDIT_12M > 0
        THEN ROUND(T8."MONTANT CREDITEUR 1M" / T8.MOY_CREDIT_12M, 2)
        ELSE 0 END AS RATIO_CREDIT_M_MOY12M,
    CASE WHEN T8.ECART_TYPE_CREDIT_12M > 1
        THEN ROUND((T8."MONTANT CREDITEUR 1M" - T8.MOY_CREDIT_12M) / T8.ECART_TYPE_CREDIT_12M, 2)
        ELSE 0 END AS ZSCORE_CREDIT_M,
    CASE WHEN T8.MOY_DEBIT_12M < 0
        THEN ROUND(ABS(T8."MONTANT DEBITEUR 1M") / ABS(T8.MOY_DEBIT_12M), 2)
        ELSE 0 END AS RATIO_DEBIT_M_MOY12M,
    CASE WHEN T8.ECART_TYPE_DEBIT_12M > 1
        THEN ROUND((T8."MONTANT DEBITEUR 1M" - T8.MOY_DEBIT_12M) / T8.ECART_TYPE_DEBIT_12M, 2)
        ELSE 0 END AS ZSCORE_DEBIT_M,
    CASE WHEN T8.ECART_TYPE_CREDIT_12M > 1
        THEN ROUND((T8."MONTANT CREDITEUR M-1" - T8.MOY_CREDIT_12M) / T8.ECART_TYPE_CREDIT_12M, 2)
        ELSE 0 END AS ZSCORE_CREDIT_M1,

    -- MOUVEMENTS CARTE
    COALESCE(T9."MONTANT_DEBITEUR_1M", 0) AS "MONTANT_DEBITEUR_1M",
    COALESCE(T9."MONTANT_DEBITEUR_6M", 0) AS "MONTANT_DEBITEUR_6M",
    COALESCE(T9."MONTANT_DEBITEUR_12M", 0) AS "MONTANT_DEBITEUR_12M",
    COALESCE(T9."NBR_DEBIT_CARTE_1M", 0) AS "NBR_DEBIT_CARTE_1M",
    COALESCE(T9."NBR_DEBIT_CARTE_6M", 0) AS "NBR_DEBIT_CARTE_6M",
    COALESCE(T9."NBR_DEBIT_CARTE_12M", 0) AS "NBR_DEBIT_CARTE_12M",
    COALESCE(T9.MOY_DEBIT_CARTE_12M, 0) AS MOY_DEBIT_CARTE_12M,
    T9.ECART_TYPE_DEBIT_CARTE_12M,
    CASE WHEN T9.MOY_DEBIT_CARTE_12M > 0
        THEN ROUND(T9."MONTANT_DEBITEUR_1M" / T9.MOY_DEBIT_CARTE_12M, 2)
        ELSE 0 END AS RATIO_DEBIT_CARTE_M_MOY12M,
    CASE WHEN T9.ECART_TYPE_DEBIT_CARTE_12M > 1
        THEN ROUND((T9."MONTANT_DEBITEUR_1M" - T9.MOY_DEBIT_CARTE_12M) / T9.ECART_TYPE_DEBIT_CARTE_12M, 2)
        ELSE 0 END AS ZSCORE_DEBIT_CARTE_M,

    -- CONNEXIONS
    LEAST(COALESCE(T10."NOMBRE CONNEXION WEB 12M", 0), 2000) AS "NOMBRE CONNEXION WEB 12M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION APPLI 12M", 0), 2000) AS "NOMBRE CONNEXION APPLI 12M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION WEB 6M", 0), 2000) AS "NOMBRE CONNEXION WEB 6M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION APPLI 6M", 0), 2000) AS "NOMBRE CONNEXION APPLI 6M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION WEB 1M", 0), 2000) AS "NOMBRE CONNEXION WEB 1M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION APPLI 1M", 0), 2000) AS "NOMBRE CONNEXION APPLI 1M",
    LEAST(COALESCE(T10."NOMBRE CONNEXION APPLI T3", 0), 2000) AS "NOMBRE CONNEXION APPLI T3",
    LEAST(COALESCE(T10."NOMBRE CONNEXION APPLI T4", 0), 2000) AS "NOMBRE CONNEXION APPLI T4",

    -- VARIABLE CIBLE
    T12.Y

FROM POPULATION_BASE T3
LEFT JOIN PROFIL_CLIENT T4 ON T3.ID_CLIENT = T4.ID_CLIENT
LEFT JOIN ENCOURS_FINAL T5 ON T3.ID_CLIENT = T5.ID_CLIENT
LEFT JOIN CLASSIFICATIONS T6 ON T3.ID_CLIENT = T6.ID_CLIENT
LEFT JOIN PRODUITS_CLIENT T7 ON T3.ID_CLIENT = T7.ID_CLIENT
LEFT JOIN MVNT_FINAL T8 ON T3.ID_CLIENT = T8.ID_CLIENT
LEFT JOIN MVNT_FINAL_CARTE T9 ON T3.ID_CLIENT = T9.ID_CLIENT
LEFT JOIN CONNEXIONS T10 ON T3.ID_CLIENT = T10.ID_CLIENT
LEFT JOIN ENCOURS_PM T11 ON T3.ID_CLIENT = T11.ID_TIERS_LIE
LEFT JOIN VARIABLE_Y T12 ON T3.ID_CLIENT = T12.ID_CLIENT
;
